name: Publish 🦆duckdb_extension_{@cookiecutter.extension_name@} 🐍📦 to PyPI

on:
  push:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_{@cookiecutter.extension_name@}/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-{@cookiecutter.extension_name@}-to-pypi.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_{@cookiecutter.extension_name@}/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-{@cookiecutter.extension_name@}-to-pypi.yml'

jobs:
  publish:
    uses: ./.github/workflows/_extension-publish.yml
    with:
      extension_name: {@cookiecutter.extension_name@}
    secrets: inherit
