name: Publish 🦆duckdb_extension_tpch 🐍📦 to PyPI

on:
  push:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_tpch/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-tpch-to-pypi.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - support_*
    paths:
      - 'extensions/duckdb_extension_tpch/**'
      - '.github/workflows/_extension-publish.yml'
      - '.github/workflows/publish-tpch-to-pypi.yml'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/_extension-publish.yml
    with:
      extension_name: tpch
    secrets: inherit
